# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
tag_permalink_style: pretty


# Setup
title:            VK2WAY
tagline:          'Jared Quinn'
description:      "Hi I'm Jared, I'm an Autodidact Polymath. Geek. Coder. Technologist.  Welcome to the shack"
url:              https://vk2way.github.io
baseurl:          /

author:
  name:           'Jared Quinn (VK2WAY)'
  url:            https://twitter.com/jaredquinn

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vk2way/vk2way.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-katex
  - jekyll-archives
  - jekyll/tagging

jekyll_admin:
  homepage: "pages"

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

