
version:          2.1.0

title:            VK2WAY
tagline:          'Jared Quinn'
description:      "Hi I'm Jared, I'm an Autodidact Polymath. Geek. Coder. Technologist.  Welcome to the shack"
url:              https://vk2way.github.io
baseurl:          /

author:
  name:           'Jared Quinn (VK2WAY)'
  url:            https://twitter.com/jaredquinn

markdown:         kramdown
highlighter:      rouge
safe:             false
debug:            true

sass:
  style: compressed

github:
  repo:           https://github.com/vk2way/vk2way.github.io

plugins:
  - jekyll-gist
  - redcarpet
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-katex
  - jekyll-postfiles
  - jekyll-paginate
#  - jekyll-paginate-v2
#
theme:            jekyll-theme-chirpy
theme_mode:       dark

permalink: '/:year/:month/:title/'

collections:
  posts:
    output: true

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

#autopages:
#  enabled: true
#  categories:
#    enabled: false
#  collections:
#    enabled: false
#  tags:
#    debug: true
#    layouts:
#      - "auto_tag.html"
#    path: "/tags/:tag"
#
#pagination:
#  enabled: true
#  collection: 'posts'
#  per_page: 10
#  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
#  title: ':title - :num of :max'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
#  extension: html
#  indexpage: 'index'
#

