markdown:         kramdown
highlighter:      rouge
safe:             false
debug:            true

# Setup
title:            VK2WAY
tagline:          'Jared Quinn'
description:      "Hi I'm Jared, I'm an Autodidact Polymath. Geek. Coder. Technologist.  Welcome to the shack"
url:              https://vk2way.github.io
baseurl:          /

author:
  name:           'Jared Quinn (VK2WAY)'
  url:            https://twitter.com/jaredquinn


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vk2way/vk2way.github.io

plugins:
  - jekyll-gist
  - redcarpet
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-katex
  - jekyll-postfiles
  - jekyll-paginate-v2

permalink: '/:year/:month/:title/'

collections:
  posts:
    output: true

autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    debug: true
    layouts:
      - "auto_tag.html"
    path: "/tags/:tag"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  title: ':title - :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  extension: html
  indexpage: 'index'


